version: '1.0.{build}'

environment:
  matrix:
    # MinGW
    - TARGET: i686-pc-windows-gnu
    - TARGET: x86_64-pc-windows-gnu

    # MSVC
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

before_build:
  - cmake .

build:
  parallel: true
  project: RakNet.sln